name: Daily Python Script

on:
  schedule:
    - cron: '0 6 * * 2-6'  # Runs at 6am UTC on Tue-Sat
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install pandas
          pip install bs4

      - name: Run script
        run: |
          python scrapy2.py
          python comex.py
          python midwest.py

      - name: Commit and push updated CSVs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "*.csv"
          git commit -m "Updated CSV's" || echo "No changes to commit"
          git push
